/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_sginventario.vistas;

import app_sginventario.controlador.EmpleadoControlador;
import app_sginventario.controlador.LoginControlador;
import app_sginventario.controlador.PrincipalControlador;

/**
 *
 * @author Johana
 */
public class PrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form PincipalVista
     */
    public PrincipalVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemGestionaEmpleados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemGestionEquipo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItemGestionComp = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        MenuItemCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("BIENVENIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu1.setText("Empleados");

        MenuItemGestionaEmpleados.setText("Gestionar empleados");
        MenuItemGestionaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGestionaEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemGestionaEmpleados);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Equipos");

        MenuItemGestionEquipo.setText("Gestionar equipos");
        jMenu2.add(MenuItemGestionEquipo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Componentes");

        MenuItemGestionComp.setText("Gestionar componentes");
        jMenu3.add(MenuItemGestionComp);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Proveedores");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Salir");

        MenuItemCerrar.setText("Cerrar sesión");
        MenuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCerrarActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItemCerrar);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCerrarActionPerformed
       
        PrincipalControlador.ocultar();
        LoginControlador.mostrar();
    }//GEN-LAST:event_MenuItemCerrarActionPerformed

    private void MenuItemGestionaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGestionaEmpleadosActionPerformed
        
        PrincipalControlador.ocultar();
        EmpleadoControlador.mostrar();
    }//GEN-LAST:event_MenuItemGestionaEmpleadosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemCerrar;
    private javax.swing.JMenuItem MenuItemGestionComp;
    private javax.swing.JMenuItem MenuItemGestionEquipo;
    private javax.swing.JMenuItem MenuItemGestionaEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
